gems:
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-feed

title: Damian Mee | Blog | Portfolio | About
email: hello@meedamian.com
description: >
  I am a developer and speaker.  My deep understanding of Bitcoin and applied
  cryptography allows me to help "blockchain startups" reach their full potential
  and find paying customers as quickly as possible.
twitter_username: meeDamian
github_username:  meeDamian

author:
  name: Damian Mee
  phone: '+66994549731'
  username: meeDamian
  twitter: meeDamian
  gist: d881897abb1b251a912d8a31c2b59298

repo:
  name: meedamian.github.io
  branch: master

url: https://meedamian.com
enforce_ssl: meeDamian.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

paginate: 3
paginate_path: "/page/:num"
permalink: /post/:title/
exclude: [README.md, Gemfile.lock, Gemfile, script, vendor]
