gems:
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-feed

title: Damian Mee | Blog | Portfolio | About
email: spam@meedamian.com
description: >
  I am a mobile developer building native apps for Android and websites
  in Node.js; currently freelancing from…
twitter_username: meeDamian
github_username:  meeDamian

author:
  name: Damian Mee
  phone: '+886909377026'
  username: meeDamian
  twitter: meeDamian

repo:
  name: meedamian.github.io
  branch: master

url: https://meedamian.com
enforce_ssl: meeDamian.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

paginate: 3
paginate_path: "/page/:num"
permalink: /post/:title/
exclude: [README.md, Gemfile.lock, Gemfile, script, vendor]
