author:
  name: Damian Mee
  phone: +886 909 377 026
  github: chester1000
  username: meeDamian

repo:
  name: chester1000.github.io
  branch: master

url: https://meeDamian.com
enforce_ssl: meeDamian.com

highlighter: pygments
markdown: redcarpet
redcarpet:
  extension: [with_toc_data]
sass:
  style: compressed
  
paginate: 3
paginate_path: "/page/:num"
permalink: /post/:title
exclude: [README.md, Gemfile.lock, Gemfile, script, vendor]
