url: "http://meeDamian.com"
githubUrl: https://github.com/chester1000
repoName: chester1000.github.io
repoBranch: master
highlighter: pygments
markdown: redcarpet
redcarpet:
  extension: [with_toc_data]
paginate: 3
paginate_path: "/page/:num"
permalink: /post/:title
exclude: [README.md, Gemfile.lock, Gemfile, script, vendor]
