gems:
  - jekyll-paginate

author:
  name: Damian Mee
  phone: '+886909377026'
  username: meeDamian

repo:
  name: meedamian.github.io
  branch: master

url: https://meeDamian.com
enforce_ssl: meeDamian.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

paginate: 3
paginate_path: "/page/:num"
permalink: /post/:title/
exclude: [README.md, Gemfile.lock, Gemfile, script, vendor]
