runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

env_variables:
  PORT: 8080

skip_files:
- ^(.*/)?.*dist/.*$
- ^(.*/)?.*~$
- ^(.*/)?.*\.DS_Store$
- ^(node_modules/.*)
- ^(.*/)?.*/node_modules/.*$

handlers:

- url: /
  script: dynamic

- url: /post/(.*)
  script: dynamic

- url: /post-content/(.*)
  script: dynamic

- url: /page/(\d+)
  script: dynamic

- url: /(.*)
  static_files: public/\1
  upload: public/