baseURL: https://meedamian.com
languageCode: en-us
title: Damian Mee
enableEmoji: true
enableRobotsTXT: true
canonifyURLs: true

params:
  themeStyle: dark
  email: hi@meedamian.com
  dateFormat: 2 Jan 2006
  favicon: /favicon.ico
  customCSS: [ css/meedamian.css ]

  home:
    localTime: true
    timeZone: Asia/Bangkok
    timeFormat: HH:mm
    numberOfProjectsToShow: 3

  social:
    - url: https://twitter.com/meeDamian
      icon: twitter
      icon_pack: fab

    - url: https://github.com/meeDamian
      icon: github
      icon_pack: fab

    - url: https://keybase.io/meeDamian
      icon: keybase
      icon_pack: fab

    - url: https://www.linkedin.com/in/meedamian/
      icon: linkedin
      icon_pack: fab

    - url: https://hodl.studio
      icon: bolt
      icon_pack: fas

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true

taxonomies:
  tag: tags
